version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli
    command: ganache -d
    ports:
      - "9999:8545"

  deployer:
    build: .
    command: "sh -c '
      npx saddle deploy OpenOraclePriceData;
      npx saddle deploy DelFiPrice 0xe78A0F7E598Cc8b0Bb87894B0F60dD2a88d6a8Ab [0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1,0xffcf8fdee72ac11b5c542428b35eef5769c409f0]
    '"
    environment:
      - PROVIDER=http://ganache:8545
    depends_on:
      - ganache

  reporter-1:
    build: sdk/javascript
    command: npm run start --private_key 0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d --script examples/fixed.js
    ports:
      - "3001:3000"

  reporter-2:
    build: sdk/javascript
    command: npm run start --private_key 0x6cbed15c793ce57650b9877cf6fa156fbef513c4e6134f022a85b1ffdd59b2a1 --script examples/fixed.js
    ports:
      - "3002:3000"

  poster:
    build: poster
    command: npm run start --
      --poster_key 0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
      --sources http://localhost:3000/prices.json,http://localhost:3001/prices.json
      --view_address 0xCfEB869F69431e42cdB54A4F4f105C19C080A601
      --web3_provider http://ganache:8545
    depends_on:
      - ganache
      - reporter-1
      - reporter-2
    restart: always
